import json

files = ['fr.json', 'en.json', 'ar.json']
paths = [f'c:\\xampp\\htdocs\\GSLC\\resources\\js\\i18n\\locales\\{f}' for f in files]

texts_fr = {
  "title": "Tarifs",
  "subtitle": "tarifs",
  "new_title": "Nouveau tarif",
  "edit_title": "Modifier le tarif",
  "unite_per_day": "par jour",
  "unite_per_container": "par conteneur",
  "unite_per_ton": "par tonne",
  "unite_flat_rate": "forfait",
  "update_ok": "Tarif mis à jour",
  "create_ok": "Tarif créé avec succès",
  "delete_ok": "Tarif supprimé",
  "delete_error": "Erreur lors de la suppression",
  "error_load": "Erreur de chargement",
  "search_placeholder": "Rechercher...",
  "all_types": "Tous les types",
  "tous_types": "Tous types",
  "all_statuses": "Tous les statuts",
  "statut_actif": "Actifs",
  "statut_inactif": "Inactifs",
  "col_code": "Code",
  "col_service": "Service",
  "col_type": "Type Conteneur",
  "col_montant": "Montant",
  "col_tva": "TVA",
  "col_validite": "Validité",
  "col_statut": "Statut",
  "no_tarifs": "Aucun tarif trouvé",
  "tva_yes": "Oui",
  "tva_no": "Non",
  "actif": "Actif",
  "inactif": "Inactif",
  "confirm_del_msg": "Supprimer le tarif",
  "f_code": "Code tarif",
  "placeholder_code": "ex: T01",
  "f_libelle": "Libellé du service",
  "placeholder_libelle": "ex: Manutention",
  "f_type": "Type conteneur",
  "f_type_all": "Tous types",
  "f_montant": "Montant unitaire",
  "f_unite": "Unité",
  "f_date_debut": "Date de début",
  "f_date_fin": "Date de fin",
  "f_tva": "TVA applicable",
  "f_actif": "Tarif actif"
}

texts_en = {
  "title": "Rates",
  "subtitle": "rates",
  "new_title": "New rate",
  "edit_title": "Edit rate",
  "unite_per_day": "per day",
  "unite_per_container": "per container",
  "unite_per_ton": "per ton",
  "unite_flat_rate": "flat rate",
  "update_ok": "Rate updated",
  "create_ok": "Rate created successfully",
  "delete_ok": "Rate deleted",
  "delete_error": "Error during deletion",
  "error_load": "Loading error",
  "search_placeholder": "Search...",
  "all_types": "All types",
  "tous_types": "All types",
  "all_statuses": "All statuses",
  "statut_actif": "Active",
  "statut_inactif": "Inactive",
  "col_code": "Code",
  "col_service": "Service",
  "col_type": "Container Type",
  "col_montant": "Amount",
  "col_tva": "VAT",
  "col_validite": "Validity",
  "col_statut": "Status",
  "no_tarifs": "No rates found",
  "tva_yes": "Yes",
  "tva_no": "No",
  "actif": "Active",
  "inactif": "Inactive",
  "confirm_del_msg": "Delete rate",
  "f_code": "Rate code",
  "placeholder_code": "e.g. T01",
  "f_libelle": "Service label",
  "placeholder_libelle": "e.g. Handling",
  "f_type": "Container type",
  "f_type_all": "All types",
  "f_montant": "Unit amount",
  "f_unite": "Unit",
  "f_date_debut": "Start date",
  "f_date_fin": "End date",
  "f_tva": "VAT applicable",
  "f_actif": "Active rate"
}

texts_ar = {
  "title": "تعريفات الخدمة",
  "subtitle": "تعريفات",
  "new_title": "تعريفة جديدة",
  "edit_title": "تعديل التعريفة",
  "unite_per_day": "في اليوم",
  "unite_per_container": "للحاوية",
  "unite_per_ton": "للطن",
  "unite_flat_rate": "مبلغ إجمالي",
  "update_ok": "تم تحديث التعريفة",
  "create_ok": "تم إنشاء التعريفة بنجاح",
  "delete_ok": "تم حذف التعريفة",
  "delete_error": "خطأ أثناء الحذف",
  "error_load": "خطأ في التحميل",
  "search_placeholder": "بحث...",
  "all_types": "جميع الأنواع",
  "tous_types": "جميع الأنواع",
  "all_statuses": "جميع الحالات",
  "statut_actif": "نشط",
  "statut_inactif": "غير نشط",
  "col_code": "الرمز",
  "col_service": "الخدمة",
  "col_type": "نوع الحاوية",
  "col_montant": "المبلغ",
  "col_tva": "ضريبة القيمة المضافة",
  "col_validite": "الصلاحية",
  "col_statut": "الحالة",
  "no_tarifs": "لم يتم العثور على تعريفات",
  "tva_yes": "نعم",
  "tva_no": "لا",
  "actif": "نشط",
  "inactif": "غير نشط",
  "confirm_del_msg": "حذف التعريفة",
  "f_code": "رمز التعريفة",
  "placeholder_code": "مثال: T01",
  "f_libelle": "تسمية الخدمة",
  "placeholder_libelle": "مثال: مناولة",
  "f_type": "نوع الحاوية",
  "f_type_all": "جميع الأنواع",
  "f_montant": "مبلغ الوحدة",
  "f_unite": "الوحدة",
  "f_date_debut": "تاريخ البدء",
  "f_date_fin": "تاريخ الانتهاء",
  "f_tva": "تطبيق الضريبة",
  "f_actif": "تعريفة نشطة"
}

texts = [texts_fr, texts_en, texts_ar]

for i, p in enumerate(paths):
    with open(p, 'r', encoding='utf-8') as f:
        data = json.load(f)
    if 'admin' not in data:
        data['admin'] = {}
    data['admin']['tarifs'] = texts[i]
    with open(p, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print('AdminTarifs locales injected.')
