<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Alertes = automatic system alerts generated by the nightly cron job (03h00).
     * Use cases:
     *   - Surestarie alert: J-3 and J-1 before franchise expires
     *   - Document expiry: 7 days before a document expires
     *   - Contract expiry: 14 days before a contract ends
     *   - Caution check: follow-up if cheque not confirmed after 5 days
     *   - Risk score: when a client's score escalates to ELEVE or CRITIQUE
     *
     * This table uses a polymorphic-style entite_type + entite_id pattern
     * (without a full Laravel morph) to keep flexibility across many entity types.
     */
    public function up(): void
    {
        Schema::create('alertes', function (Blueprint $table) {
            $table->id();

            // Type of alert (matches cron job trigger)
            $table->enum('type_alerte', [
                'SURESTARIE_J3',             // Franchise expires in 3 days
                'SURESTARIE_J1',             // Franchise expires tomorrow
                'SURESTARIE_DEPASSEE',       // Franchise already exceeded
                'DOCUMENT_EXPIRATION',       // A required document expires soon
                'CONTRAT_EXPIRATION',        // Contract nearing end date
                'CAUTION_NON_CONFIRMEE',     // Cheque deposit not confirmed
                'SCORE_RISQUE_ELEVE',        // Client risk score escalated
                'SCORE_RISQUE_CRITIQUE',     // Client risk score critical
                'DEVIS_EXPIRE',              // A devis passed its expiry date
                'PAIEMENT_EN_RETARD',        // Invoice overdue
                'AUTRE',
            ]);

            // Severity level — drives UI badge color and notification priority
            $table->enum('niveau', [
                'INFO',      // Informational — no action required immediately
                'ATTENTION', // Warning — action needed soon
                'CRITIQUE',  // Critical — immediate action required
            ])->default('ATTENTION');

            // Polymorphic entity reference (manual, not Laravel morph)
            $table->string('entite_type', 60)->nullable();
            // e.g. 'contrat', 'document', 'client', 'demande'
            $table->unsignedBigInteger('entite_id')->nullable();

            // Human-readable alert message (generated by cron job)
            $table->text('message');

            // Optional metadata from cron (e.g. days remaining, score value)
            $table->json('meta')->nullable();

            // Who should see this alert (nullable = visible to all relevant roles)
            $table->foreignId('destinataire_user_id')
                  ->nullable()
                  ->constrained('users')
                  ->nullOnDelete();

            // Has the alert been read in the dashboard?
            $table->boolean('est_lue')->default(false);
            $table->timestamp('lue_le')->nullable();

            // Has a NASHCO agent acted on it?
            $table->boolean('est_traitee')->default(false);
            $table->foreignId('traitee_par_user_id')
                  ->nullable()
                  ->constrained('users')
                  ->nullOnDelete();
            $table->timestamp('date_traitement')->nullable();
            $table->text('note_traitement')->nullable();

            $table->timestamps();

            // Index for common dashboard queries
            $table->index(['est_lue', 'est_traitee', 'niveau']);
            $table->index(['entite_type', 'entite_id']);
            $table->index('destinataire_user_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('alertes');
    }
};
